version: '3'
services:
  app:
    container_name: business-ratings
    image: business-ratings
    build: .
    command: ['npm', 'start']
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
